#!/bin/bash

REPO_DIR=$(realpath .)

BASHRC_PATH=~/.bashrc
EXPORT_THETA_CONFIG_DIR_STATEMENT="export THETA_CONFIG_DIR=$REPO_DIR"
SOURCE_ALIAS_FILE_STATEMENT="source $REPO_DIR/aliases.sh"
SOURCE_FUNCTIONS_FILE_STATEMENT="source $REPO_DIR/functions.sh"

grep -q "$EXPORT_THETA_CONFIG_DIR_STATEMENT" $BASHRC_PATH
ZERO_IF_THETA_CONFIG_DIR_EXPORTED=$?
grep -q "$SOURCE_ALIAS_FILE_STATEMENT" $BASHRC_PATH
ZERO_IF_ALIAS_SOURCED=$?
grep -q "$SOURCE_FUNCTIONS_FILE_STATEMENT" $BASHRC_PATH
ZERO_IF_FUNCTIONS_SOURCED=$?

if [[ $ZERO_IF_THETA_CONFIG_DIR_EXPORTED == 0 ]]; then
	echo "$EXPORT_THETA_CONFIG_DIR_STATEMENT present in $BASHRC_PATH"
else
	echo "$EXPORT_THETA_CONFIG_DIR_STATEMENT absent from $BASHRC_PATH"
	echo "$EXPORT_THETA_CONFIG_DIR_STATEMENT" >> $BASHRC_PATH
fi

if [[ $ZERO_IF_ALIAS_SOURCED == 0 ]]; then
	echo "$SOURCE_ALIAS_FILE_STATEMENT present in $BASHRC_PATH"
else
	echo "$SOURCE_ALIAS_FILE_STATEMENT absent from $BASHRC_PATH"
	echo "$SOURCE_ALIAS_FILE_STATEMENT" >> $BASHRC_PATH
fi

if [[ $ZERO_IF_FUNCTIONS_SOURCED == 0 ]]; then
	echo "$SOURCE_FUNCTIONS_FILE_STATEMENT present in $BASHRC_PATH"
else
	echo "$SOURCE_FUNCTIONS_FILE_STATEMENT absent from $BASHRC_PATH"
	echo "$SOURCE_FUNCTIONS_FILE_STATEMENT" >> $BASHRC_PATH
fi
